
[functions.webhook-event-logger]
enabled = true
verify_jwt = true
import_map = "./functions/webhook-event-logger/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/webhook-event-logger/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/webhook-event-logger/*.html" ]

[functions.webhook-external-notifier]
enabled = true
verify_jwt = true
import_map = "./functions/webhook-external-notifier/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/webhook-external-notifier/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/webhook-external-notifier/*.html" ]
