version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres_animal:
    image: postgres:17
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: animal_db
    ports:
      - "5434:5432"

  postgres_adoption:
    image: postgres:17
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: adoption_db
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
